package persistence

import persistence.slickWrapper.Driver.api._

package object schema {
  /**
   * This SQL type should be used as a backend for [[com.typesafe.config.Config]].
   */
  val configSQLType = s"VARCHAR(65000)"

  /**
   * This SQL type is used for storing job results
   */
  val resultSqlType = configSQLType

  /**
   * Table tags
   */
  val jobsTable = "JOBS"
  val contextsTable = "CONTEXTS"

  /**
   * Tables: entry points for table schema
   */
  val jobs = TableQuery[Jobs]
  val contexts = TableQuery[Contexts]

  /**
   * Add here tables which should be created during server start.
   */
  val autoGeneratedTables = List(
    (contextsTable, contexts.schema),
    (jobsTable, jobs.schema)
  )
}
